global:
  scrape_interval: 15s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'filmotek'
    static_configs:
      - targets: ['filmotek:8080']