on:
  push:
    branches:
      - main
      - feature
jobs:
  build:
    runs-on:
      ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20', '1.21', '1.22']
    steps:
      - name: Get Code
        uses: actions/checkout@v2
      - name: Setup go ${{matrix.go-version}}
        uses: actions/setup-go@v4
        with:
          go-version: ${{matrix.go-version}}
      - name: Display go version
        run: go version
      - name: satisfy dependencies
        run: go get .
      - name: Testing
        run: go test ./... -json > TestResults-${{ matrix.go-version }}.json
      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results-${{ matrix.go-version }}
          path: TestResults-${{ matrix.go-version }}.json

